### ISSUE TITLE
Promedio

### ISSUE THREAD

**Issue by dengayet** [fiuba-labo-de-micro-miercoles/2019-2c-primer-proyecto-dengayet#1]
Hola! Con Agustín D'Amico hicimos el ejercicio del promedio del vector.
Tenemos una duda: tanto  hacer **LDI ZL, LOW(2*DATA)** como hacer **LDI ZL, LOW(DATA)** da el mismo resultado y no entendemos por qué. 
Gracias!
Saludos

**Comment by pimartos** [comment]
Hola, un par de comentarios:
1) El micro empieza a ejecutar a partir del RESET_VECTOR (0x0000 de memoria de programa); por lo que no es buena idea poner una tabla al inicio del .cseg, ya que la misma queda en la posicion 0x0000. El simulador se da cuenta que esta pasando esto y empieza a ejecutar a partir de 0x0006; pero en un micro real esto no funciona. Las tablas deben colocarse despues del codigo assembler (si van a las assembler options y habilitan create list file, van a ver como queda la tabla mapeada a posiciones de memoria de programa y el hexa equivalente de cada instruccion)
2) por la razon anterior, DATA vale 0x0000, entonces LOW(DATA)=LOW(2*DATA)=0x00 

cordialmente,
Pedro

**Comment by dengayet** [comment]
Ahí me quedó claro, muchas gracias!

Saludos
Denise
